// app/metadata.ts
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Shrirama Temple, Hariharapallathadka',
  description: 'Explore the spiritual heritage of Shrirama Temple in Hariharapallathadka, Karnataka. Discover its rich history, unique architecture, and religious significance.',
  keywords: [
    'Shrirama Temple',
    'Hariharapallathadka',
    'Karnataka temples',
    'Lord Harihara',
    'Vishnu and Shiva',
    'Hindu pilgrimage',
    'Triveni Sangam',
    'Tula Sankramana',
    'Shani Pooja',
    'sacred confluence',
    'spiritual tourism',
    'Kukke Subrahmanya',
    'Subrahmanya',
    'Kulkunda',
    'Kulkunda Shree Basaveshwara Temple',
    'Kulkunda Shri Basaveshwara Temple',
    'Basavanamoola',
    'Basavanamoola Shree Basaveshwara Temple',
    'Basavanamoola Shri Basaveshwara Temple',
    'Shrirama Temple',
    'Shrirama Temple',
    'Sri Rama Temple',
    'Shrirama Temple Hariharapallathadka',
    'Shrirama Temple Hariharapallathadka',
    'Rudrabhishekam',
    'Lord Shiva',
    'Lord Vishnu',
    'Lord Mahaganapathi',
    'Lord Ganesha',
    'Lord Subrahmanya',
    'Champashasti',
    'Shree Basaveshwara Temple, Hindu temple, Basavanamoola, Kulkunda, Lord Shiva, Kukke Subrahmanya,Kukke Shree Subrahmanya Temple, sacred place, cultural significance,historical place,Bisle Ghats,Tulunadu,Temples in Coastal Karnataka,Temples in Kukke Subrahmanya,Nearby places in Subrahmanya,places to visit,places to visit at Subrahmanya,Nearby temples to Kukke Shri Subrahmanya Temple,Dharmasthala,Shri Kshethra Dharmasthala,Kulkunda Shree Basaveshwara Temple, Kukke Shri Subrahmanya Temple, Adi Subrahmanya Temple, Shri Subrahmanya Mutt, Kashikatte Shri Ganapathi Temple, Biladwara, Shri Vanadurga Devi Temple, Shree Abhaya Mahaganapathi, Agrahara Shri Somanatha Temple, Shrirama Temple, Kumaradhara River (Bathing Ghat), Shri Kshethra Dharmasthala, Bisle Ghat Viewpoint, Patla Betta, Mallalli Falls, Hindu temples, Karnataka, Western Ghats, Serpent king Vasuki, Kumaraparvatha, Dharmasthala Manjunatha Swamy Temple, Free meals, Jain Pergade family, Bisle Ghat, Somwarpet, Coorg, Monsoon season, Nature enthusiasts, Trekkers,Kumara Parvatha trek,Kumara Parvatha trekking,Shesha Parvatha,South India treks,South India Temples,Karnataka Hikers,Karnataka Trekkers,Bhattaramane,Bhattas house,Bhattara Mane,Treks in Karnataka,Treks in Western Ghats,Treks in South India,Toughest treks, Western Ghats landscapes',
   'Dakshina Kannada temples', 'Lord Harihara', 'Vishnu and Shiva fusion', 'Hindu pilgrimage sites in Karnataka', 'Triveni Sangam', 'Tula Sankramana festival', 'Shani Pooja rituals', 'sacred river confluence', 'spiritual tourism in South India', 'Western Ghats temples', 'ancient Indian temples', 'Karnataka religious sites', 'temples near Sullia', 'Harihara deity worship', 'Koti Theertha significance', 'Pallathadka village attractions', 'temples in Western Ghats', 'Karnataka cultural heritage',
    'Shrirama Temple', 'Hariharapallathadka', 'Dakshina Kannada temples', 'Lord Harihara', 'Vishnu and Shiva fusion', 'Hindu pilgrimage sites in Karnataka', 'Triveni Sangam', 'Tula Sankramana festival', 'Shani Pooja rituals', 'sacred river confluence', 'spiritual tourism in South India', 'Western Ghats temples', 'ancient Indian temples', 'Karnataka religious sites', 'temples near Sullia', 'Harihara deity worship', 'Koti Theertha significance', 'Pallathadka village attractions', 'temples in Western Ghats', 'Karnataka cultural heritage', 'Kukke Subrahmanya Temple', 'Subrahmanya', 'Kulkunda', 'Kulkunda Shree Basaveshwara Temple', 'Basavanamoola', 'Basavanamoola Shree Basaveshwara Temple'
  ],
  authors: [{ name: 'Shrirama Temple' }],
  openGraph: {
    title: 'Shrirama Temple, Hariharapallathadka',
    description: 'Discover the divine amalgamation of Lord Vishnu and Lord Shiva at Shrirama Temple in Hariharapallathadka, Karnataka.',
    url: 'https://www.shriharihareshwara.org',
    siteName: 'Shrirama Temple',
    images: [
      {
        url: '/logo.jpg',
        width: 800,
        height: 600,
        alt: 'Shrirama Temple Logo',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  icons: {
    icon: [
      { url: '/logo.jpg', type: 'image/jpeg', sizes: '48x48' },
      { url: '/logo.jpg', type: 'image/jpeg', sizes: '32x32' },
      { url: '/logo.jpg', type: 'image/jpeg', sizes: '16x16' },
    ],
    shortcut: { url: '/logo.jpg', type: 'image/jpeg' },
    apple: { url: '/logo.jpg', type: 'image/jpeg' },
  },
};